# Config File for Ves Collector

# Server configuration
server:
  host: "0.0.0.0" # Host IP address
  port: 9999 # Port number
  debug: true # Debug mode

ves:
  api_version: "v5"

# Kafka configuration
kafka:
  host: "kafka.nonrtric.svc.cluster.local" # Kafka host
  port: 9092 # Kafka port number
  default_topic: "ves" # Default Kafka topic

# Logging configuration
logging:
  level: INFO # Logging level