apiVersion: apps/v1
kind: Deployment
metadata:
  name: ves-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ves-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ves-collector
  template:
    metadata:
      labels:
        app: ves-collector
    spec:
      containers:
      - name: ves-collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.server.port }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.server.port }}
          initialDelaySeconds: 3
          periodSeconds: 60
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true

      volumes:
      - name: config-volume
        configMap:
          name: ves-collector-config
          items:
          - key: config.yaml
            path: config.yaml
